# Generated by Django 5.2.3 on 2026-09-18 12:49

import django.db.models.deletion
from django.db import migrations, models


def poblar_instituciones(apps, schema_editor):
    UsuarioPerfil = apps.get_model('core', 'UsuarioPerfil')
    for perfil in UsuarioPerfil.objects.filter(id_institucion__isnull=False):
        perfil.instituciones.add(perfil.id_institucion)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicaluser'),
        ('oficios', '0043_alter_historicaloficio_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='instituciones',
            field=models.ManyToManyField(blank=True, related_name='perfiles_asignados', to='oficios.institucion', verbose_name='Instituciones'),
        ),
        migrations.AlterField(
            model_name='historicalusuarioperfil',
            name='id_institucion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oficios.institucion', verbose_name='Institución Principal'),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='id_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='oficios.institucion', verbose_name='Institución Principal'),
        ),
        migrations.RunPython(poblar_instituciones, reverse_code=migrations.RunPython.noop),
    ]

