# Generated by Django 5.2.7 on 2025-10-20 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0004_nino_edad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MPA', 'MPA'), ('JUDICIAL', 'Judicial')], default='MPA', max_length=10, verbose_name='Tipo de Caso')),
                ('expte', models.CharField(max_length=50, unique=True, verbose_name='Expediente')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=15, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='CasoNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_relacion', models.DateField(auto_now_add=True, verbose_name='Fecha de relación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caso_ninos', to='casos.caso', verbose_name='Caso')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caso_ninos', to='personas.nino', verbose_name='Niño')),
            ],
            options={
                'verbose_name': 'Relación Caso-Niño',
                'verbose_name_plural': 'Relaciones Caso-Niño',
                'unique_together': {('caso', 'nino')},
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='ninos',
            field=models.ManyToManyField(blank=True, related_name='casos', through='casos.CasoNino', through_fields=('caso', 'nino'), to='personas.nino', verbose_name='Niños relacionados'),
        ),
        migrations.CreateModel(
            name='CasoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_relacion', models.DateField(auto_now_add=True, verbose_name='Fecha de relación')),
                ('tipo_relacion', models.CharField(help_text='Ej: Padre, Madre, Tutor, Representante Legal, etc.', max_length=100, verbose_name='Tipo de relación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caso_partes', to='casos.caso', verbose_name='Caso')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caso_partes', to='personas.parte', verbose_name='Parte')),
            ],
            options={
                'verbose_name': 'Relación Caso-Parte',
                'verbose_name_plural': 'Relaciones Caso-Parte',
                'unique_together': {('caso', 'parte', 'tipo_relacion')},
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='partes',
            field=models.ManyToManyField(blank=True, related_name='casos', through='casos.CasoParte', through_fields=('caso', 'parte'), to='personas.parte', verbose_name='Partes relacionadas'),
        ),
    ]
