# Generated by Django 5.2.7 on 2026-01-27 12:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_alter_caso_expte'),
        ('personas', '0007_nino_domicilios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casonino',
            options={'verbose_name': 'Relacion Caso-Nino', 'verbose_name_plural': 'Relaciones Caso-Nino'},
        ),
        migrations.AlterModelOptions(
            name='casoparte',
            options={'verbose_name': 'Relacion Caso-Parte', 'verbose_name_plural': 'Relaciones Caso-Parte'},
        ),
        migrations.AlterField(
            model_name='caso',
            name='tipo',
            field=models.CharField(choices=[('MPA', 'MPA'), ('JUDICIAL', 'Judicial'), ('PROVINCIAL', 'Provincial'), ('NOTA', 'Nota')], default='MPA', max_length=10, verbose_name='Tipo de Caso'),
        ),
        migrations.AlterUniqueTogether(
            name='casoparte',
            unique_together={('caso', 'parte')},
        ),
        migrations.CreateModel(
            name='HistoricalCaso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MPA', 'MPA'), ('JUDICIAL', 'Judicial'), ('PROVINCIAL', 'Provincial'), ('NOTA', 'Nota')], default='MPA', max_length=10, verbose_name='Tipo de Caso')),
                ('expte', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Expediente')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=15, verbose_name='Estado')),
                ('creado', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Caso',
                'verbose_name_plural': 'historical Casos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
