# Generated by Django 5.2.7 on 2026-04-09 00:00

from django.db import migrations, models


def poblar_codigos_casos(apps, schema_editor):
    Caso = apps.get_model('casos', 'Caso')
    secuencias = {}

    for caso in Caso.objects.order_by('creado', 'id'):
        if caso.codigo:
            try:
                _, numero, anio = caso.codigo.split('-')
                anio = int(anio)
                numero = int(numero)
                secuencias[anio] = max(secuencias.get(anio, 0), numero)
            except (TypeError, ValueError):
                pass
            continue

        fecha_base = caso.creado
        anio = fecha_base.year if fecha_base else 2026
        secuencias[anio] = secuencias.get(anio, 0) + 1
        caso.codigo = f"CS-{secuencias[anio]:05d}-{anio}"
        caso.save(update_fields=['codigo'])


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_alter_casonino_options_alter_casoparte_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='historicalcaso',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.RunPython(poblar_codigos_casos, migrations.RunPython.noop),
    ]
