# Generated by Django 5.2.7 on 2026-05-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_caso_codigo_historicalcaso_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='expte',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalcaso',
            name='expte',
        ),
        migrations.RemoveField(
            model_name='historicalcaso',
            name='tipo',
        ),
    ]
