# Generated by Django 5.2.3 on 2025-10-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
    ]
