# Generated by Django 5.2.7 on 2025-10-13 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0002_load_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Juzgado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Juzgado',
                'verbose_name_plural': 'Juzgados',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='agente',
        ),
        migrations.AddField(
            model_name='oficio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='tipo',
            field=models.CharField(choices=[('MPA', 'MPA'), ('Judicial', 'Judicial')], max_length=20, verbose_name='Tipo de Oficio'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to='oficios.juzgado', verbose_name='Juzgado'),
        ),
        migrations.DeleteModel(
            name='Agente',
        ),
    ]
