# Generated by Django 5.2.7 on 2025-10-14 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0003_juzgado_remove_oficio_agente_oficio_usuario_and_more'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_relacion', models.DateField(auto_now_add=True, verbose_name='Fecha de relación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficio_ninos', to='personas.nino', verbose_name='Niño')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficio_ninos', to='oficios.oficio', verbose_name='Oficio')),
            ],
            options={
                'verbose_name': 'Relación Oficio-Niño',
                'verbose_name_plural': 'Relaciones Oficio-Niño',
                'unique_together': {('oficio', 'nino')},
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='ninos',
            field=models.ManyToManyField(blank=True, related_name='oficios', through='oficios.OficioNino', through_fields=('oficio', 'nino'), to='personas.nino', verbose_name='Niños relacionados'),
        ),
    ]
