# Generated by Django 5.2.7 on 2025-10-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0004_oficionino_oficio_ninos'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_relacion', models.DateField(auto_now_add=True, verbose_name='Fecha de relación')),
                ('tipo_relacion', models.CharField(help_text='Ej: Padre, Madre, Tutor, Representante Legal, etc.', max_length=100, verbose_name='Tipo de relación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficio_partes', to='oficios.oficio', verbose_name='Oficio')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficio_partes', to='personas.parte', verbose_name='Parte')),
            ],
            options={
                'verbose_name': 'Relación Oficio-Parte',
                'verbose_name_plural': 'Relaciones Oficio-Parte',
                'unique_together': {('oficio', 'parte', 'tipo_relacion')},
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='partes',
            field=models.ManyToManyField(blank=True, related_name='oficios', through='oficios.OficioParte', through_fields=('oficio', 'parte'), to='personas.parte', verbose_name='Partes relacionadas'),
        ),
    ]
