# Generated by Django 5.2.7 on 2025-10-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0005_oficioparte_oficio_partes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juzgado',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='juzgado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
