# Generated by Django 5.2.7 on 2025-10-15 11:42

import django.core.validators
import oficios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0006_remove_juzgado_descripcion_juzgado_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Sube el archivo PDF del oficio. Tamaño máximo: 10MB.', null=True, upload_to=oficios.models.oficio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF.')], verbose_name='Archivo PDF del oficio'),
        ),
    ]
