# Generated by Django 5.2.7 on 2025-10-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0007_oficio_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='estado',
            field=models.CharField(choices=[('cargado', 'Cargado'), ('asignado', 'Asignado'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto')], default='cargado', max_length=20, verbose_name='Estado'),
        ),
    ]
