# Generated by Django 5.2.7 on 2025-10-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0008_remove_caratula_oficio_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='caratula_oficio',
        ),
        migrations.DeleteModel(
            name='CaratulaOficio',
        ),
    ]
