# Generated by Django 5.2.7 on 2025-10-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0009_remove_caratula_oficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaratulaOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Carátula de Oficio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carátula de Oficio',
                'verbose_name_plural': 'Carátulas de Oficio',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='caratula_oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios_caratula', to='oficios.caratulaoficio', verbose_name='Carátula de Oficio'),
        ),
    ]
