# Generated by Django 5.2.7 on 2025-10-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0010_add_caratula_oficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='caratula_oficio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carátula de Oficio'),
        ),
    ]
