# Generated by Django 5.2.7 on 2025-10-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0011_alter_oficio_caratula_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='nro_oficio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Oficio'),
        ),
    ]
