# Generated by Django 5.2.7 on 2025-10-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
        ('oficios', '0012_oficio_nro_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='caso',
            field=models.ForeignKey(blank=True, help_text='Caso al que pertenece este oficio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='casos.caso', verbose_name='Caso relacionado'),
        ),
    ]
