# Generated by Django 5.2.7 on 2025-10-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0013_oficio_caso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='ninos',
        ),
        migrations.AlterUniqueTogether(
            name='oficioparte',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='oficioparte',
            name='oficio',
        ),
        migrations.RemoveField(
            model_name='oficioparte',
            name='parte',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='partes',
        ),
        migrations.DeleteModel(
            name='OficioNino',
        ),
        migrations.DeleteModel(
            name='OficioParte',
        ),
    ]
