# Generated by Django 5.2.7 on 2025-10-21 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0014_remove_oficio_ninos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('creado', 'Creado'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('creado', 'Creado'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Nuevo Estado')),
                ('detalle', models.TextField(blank=True, help_text='Descripción detallada del movimiento o cambio realizado', verbose_name='Detalle del movimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Documento relacionado con este movimiento (opcional)', null=True, upload_to='movimientos_oficios/', verbose_name='Archivo adjunto')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_oficios', to='oficios.institucion', verbose_name='Institución')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='oficios.oficio', verbose_name='Oficio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_oficios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Oficio',
                'verbose_name_plural': 'Movimientos de Oficios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
