# Generated by Django 5.2.7 on 2025-10-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0015_movimientooficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientooficio',
            name='archivo_adjunto',
        ),
    ]
