# Generated by Django 5.2.7 on 2025-10-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0016_remove_movimientooficio_archivo_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientooficio',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('cargado', 'Cargado'), ('asignado', 'Asignado'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto')], max_length=20, null=True, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='estado_nuevo',
            field=models.CharField(choices=[('cargado', 'Cargado'), ('asignado', 'Asignado'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto')], max_length=20, verbose_name='Nuevo Estado'),
        ),
    ]
