# Generated by Django 5.2.7 on 2025-10-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0019_remove_tipo_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='expte',
        ),
        migrations.AddField(
            model_name='oficio',
            name='denuncia',
            field=models.CharField(blank=True, help_text='Número de denuncia relacionada al oficio', max_length=50, null=True, verbose_name='Número de Denuncia'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='legajo',
            field=models.CharField(blank=True, help_text='Número de legajo relacionado al oficio', max_length=50, null=True, verbose_name='Número de Legajo'),
        ),
    ]
