# Generated by Django 5.2.7 on 2025-10-24 11:32

import django.core.validators
import django.db.models.deletion
import oficios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0020_remove_expte_add_denuncia_legajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle de la respuesta')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Sube el archivo PDF de la respuesta. Tamaño máximo: 10MB.', null=True, upload_to=oficios.models.respuesta_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF.')], verbose_name='Archivo PDF de la respuesta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='oficios.oficio', verbose_name='Oficio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_oficios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
