# Generated by Django 5.2.7 on 2025-10-24 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0022_update_respuesta_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.TextField(blank=True, verbose_name='Respuesta'),
        ),
    ]
