# Generated by Django 5.2.7 on 2025-10-24 12:51

import django.core.validators
import oficios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0023_remove_respuesta_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientooficio',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=oficios.models.movimiento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF.')], verbose_name='Archivo PDF del movimiento'),
        ),
    ]
