# Generated by Django 5.2.3 on 2025-11-13 14:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import oficios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0026_respuesta_id_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caratula',
            options={'ordering': ['nombre'], 'verbose_name': 'CarÃ¡tula', 'verbose_name_plural': 'CarÃ¡tulas'},
        ),
        migrations.AlterModelOptions(
            name='caratulaoficio',
            options={'ordering': ['nombre'], 'verbose_name': 'CarÃ¡tula de Oficio', 'verbose_name_plural': 'CarÃ¡tulas de Oficio'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre'], 'verbose_name': 'InstituciÃ³n', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AddField(
            model_name='oficio',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envio'),
        ),
        migrations.AlterField(
            model_name='caratula',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la CarÃ¡tula'),
        ),
        migrations.AlterField(
            model_name='caratulaoficio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='caratulaoficio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la CarÃ¡tula de Oficio'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='DirecciÃ³n'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la InstituciÃ³n'),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='DirecciÃ³n'),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TelÃ©fono'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='detalle',
            field=models.TextField(blank=True, help_text='DescripciÃ³n detallada del movimiento o cambio realizado', verbose_name='Detalle del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_oficios', to='oficios.institucion', verbose_name='InstituciÃ³n'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Ãšltima actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Sube el archivo PDF del oficio. TamaÃ±o mÃ¡ximo: 10MB.', null=True, upload_to=oficios.models.oficio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF.')], verbose_name='Archivo PDF del oficio'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='caratula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to='oficios.caratula', verbose_name='CarÃ¡tula'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='caratula_oficio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CarÃ¡tula de Oficio'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='denuncia',
            field=models.CharField(blank=True, help_text='NÃºmero de denuncia relacionada al oficio', max_length=50, null=True, verbose_name='NÃºmero de Denuncia'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de emisiÃ³n'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to='oficios.institucion', verbose_name='InstituciÃ³n'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='legajo',
            field=models.CharField(blank=True, help_text='NÃºmero de legajo relacionado al oficio', max_length=50, null=True, verbose_name='NÃºmero de Legajo'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='nro_oficio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NÃºmero de Oficio'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='oficios.institucion', verbose_name='InstituciÃ³n'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='ModificaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_pdf',
            field=models.FileField(blank=True, help_text='Sube el archivo PDF de la respuesta. TamaÃ±o mÃ¡ximo: 10MB.', null=True, upload_to=oficios.models.respuesta_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF.')], verbose_name='Archivo PDF de la respuesta'),
        ),
    ]
