# Generated by Django 5.2.3 on 2025-11-19 15:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import oficios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0027_alter_caratula_options_alter_caratulaoficio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaJuzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Juzgado',
                'verbose_name_plural': 'Categorías de Juzgado',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='caratula',
            options={'ordering': ['nombre'], 'verbose_name': 'Carátula', 'verbose_name_plural': 'Carátulas'},
        ),
        migrations.AlterModelOptions(
            name='caratulaoficio',
            options={'ordering': ['nombre'], 'verbose_name': 'Carátula de Oficio', 'verbose_name_plural': 'Carátulas de Oficio'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre'], 'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='detalle',
            field=models.TextField(blank=True, help_text='Descripción detallada del movimiento o cambio realizado', verbose_name='Detalle del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_oficios', to='oficios.institucion', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Sube el archivo PDF del oficio. Tamaño máximo: 10MB.', null=True, upload_to=oficios.models.oficio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF.')], verbose_name='Archivo PDF del oficio'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='caratula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to='oficios.caratula', verbose_name='Carátula'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='caratula_oficio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carátula de Oficio'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='denuncia',
            field=models.CharField(blank=True, help_text='Número de denuncia relacionada al oficio', max_length=50, null=True, verbose_name='Número de Denuncia'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to='oficios.institucion', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='legajo',
            field=models.CharField(blank=True, help_text='Número de legajo relacionado al oficio', max_length=50, null=True, verbose_name='Número de Legajo'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='nro_oficio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Oficio'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='oficios.institucion', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificación'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_pdf',
            field=models.FileField(blank=True, help_text='Sube el archivo PDF de la respuesta. Tamaño máximo: 10MB.', null=True, upload_to=oficios.models.respuesta_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF.')], verbose_name='Archivo PDF de la respuesta'),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juzgados', to='oficios.categoriajuzgado', verbose_name='Categoría'),
        ),
    ]
