# Generated by Django 5.2.7 on 2026-01-27 12:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_alter_casonino_options_alter_casoparte_options_and_more'),
        ('oficios', '0030_oficio_validaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratula',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Carátula'),
        ),
        migrations.AlterField(
            model_name='caratulaoficio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='caratulaoficio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Carátula de Oficio'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='plazo_horas',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo'),
        ),
        migrations.CreateModel(
            name='HistoricalInstitucion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Institución')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('actualizado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Institución',
                'verbose_name_plural': 'historical Instituciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJuzgado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Juzgado')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('actualizado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oficios.categoriajuzgado', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'historical Juzgado',
                'verbose_name_plural': 'historical Juzgados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOficio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nro_oficio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Oficio')),
                ('denuncia', models.CharField(blank=True, help_text='Número de denuncia relacionada al oficio', max_length=50, null=True, verbose_name='Número de Denuncia')),
                ('legajo', models.CharField(blank=True, help_text='Número de legajo relacionado al oficio', max_length=50, null=True, verbose_name='Número de Legajo')),
                ('estado', models.CharField(choices=[('cargado', 'Cargado'), ('asignado', 'Asignado'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto')], default='cargado', max_length=20, verbose_name='Estado')),
                ('plazo_horas', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envio')),
                ('caratula_oficio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carátula de Oficio')),
                ('validado_coord', models.BooleanField(default=False, verbose_name='Validado por coordinación')),
                ('validado_director', models.BooleanField(default=False, verbose_name='Validado por director')),
                ('creado', models.DateTimeField(blank=True, editable=False, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('archivo_pdf', models.TextField(blank=True, help_text='Sube el archivo PDF del oficio. Tamaño máximo: 10MB.', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF.')], verbose_name='Archivo PDF del oficio')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('caratula', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oficios.caratula', verbose_name='Carátula')),
                ('caso', models.ForeignKey(blank=True, db_constraint=False, help_text='Caso al que pertenece este oficio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='casos.caso', verbose_name='Caso relacionado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oficios.institucion', verbose_name='Institución')),
                ('juzgado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='oficios.juzgado', verbose_name='Juzgado')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Oficio',
                'verbose_name_plural': 'historical Oficios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
