# Generated by Django 5.2.7 on 2026-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0031_alter_caratula_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientooficio',
            name='validado_coord',
            field=models.BooleanField(default=False, verbose_name='Validado por coordinación'),
        ),
        migrations.AddField(
            model_name='movimientooficio',
            name='validado_director',
            field=models.BooleanField(default=False, verbose_name='Validado por director'),
        ),
    ]
