# Generated by Django 5.2.7 on 2026-04-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0032_movimientooficio_validado_coord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloficio',
            name='incompetencia',
            field=models.BooleanField(default=False, verbose_name='Incompetencia'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='incompetencia',
            field=models.BooleanField(default=False, verbose_name='Incompetencia'),
        ),
    ]
