# Generated by Django 5.2.7 on 2026-04-09 00:00

from django.db import migrations, models
from django.utils import timezone


def poblar_codigos_oficios(apps, schema_editor):
    Oficio = apps.get_model('oficios', 'Oficio')
    secuencias = {}

    for oficio in Oficio.objects.order_by('fecha_emision', 'creado', 'id'):
        if oficio.codigo:
            try:
                _, numero, anio = oficio.codigo.split('-')
                anio = int(anio)
                numero = int(numero)
                secuencias[anio] = max(secuencias.get(anio, 0), numero)
            except (TypeError, ValueError):
                pass
            continue

        fecha_base = oficio.fecha_emision or oficio.creado or timezone.now()
        if timezone.is_aware(fecha_base):
            fecha_base = timezone.localtime(fecha_base)
        anio = fecha_base.year
        secuencias[anio] = secuencias.get(anio, 0) + 1
        oficio.codigo = f"OF-{secuencias[anio]:05d}-{anio}"
        oficio.save(update_fields=['codigo'])


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0034_alter_historicaloficio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloficio',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Código interno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código interno'),
        ),
        migrations.RunPython(poblar_codigos_oficios, migrations.RunPython.noop),
    ]
