# Generated by Django 5.2.7 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0035_oficio_codigo_historicaloficio_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloficio',
            name='estado',
            field=models.CharField(
                choices=[
                    ('cargado', 'Cargado'),
                    ('asignado', 'Asignado'),
                    ('derivado', 'Derivado'),
                    ('respondido', 'Respondido'),
                    ('enviado', 'Enviado'),
                    ('devuelto', 'Devuelto'),
                    ('incompetencia', 'Incompetencia'),
                ],
                default='cargado',
                max_length=20,
                verbose_name='Estado',
            ),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='estado_anterior',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cargado', 'Cargado'),
                    ('asignado', 'Asignado'),
                    ('derivado', 'Derivado'),
                    ('respondido', 'Respondido'),
                    ('enviado', 'Enviado'),
                    ('devuelto', 'Devuelto'),
                    ('incompetencia', 'Incompetencia'),
                ],
                max_length=20,
                null=True,
                verbose_name='Estado Anterior',
            ),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='estado_nuevo',
            field=models.CharField(
                choices=[
                    ('cargado', 'Cargado'),
                    ('asignado', 'Asignado'),
                    ('derivado', 'Derivado'),
                    ('respondido', 'Respondido'),
                    ('enviado', 'Enviado'),
                    ('devuelto', 'Devuelto'),
                    ('incompetencia', 'Incompetencia'),
                ],
                max_length=20,
                verbose_name='Nuevo Estado',
            ),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='estado',
            field=models.CharField(
                choices=[
                    ('cargado', 'Cargado'),
                    ('asignado', 'Asignado'),
                    ('derivado', 'Derivado'),
                    ('respondido', 'Respondido'),
                    ('enviado', 'Enviado'),
                    ('devuelto', 'Devuelto'),
                    ('incompetencia', 'Incompetencia'),
                ],
                default='cargado',
                max_length=20,
                verbose_name='Estado',
            ),
        ),
    ]
