# Generated by Django 5.2.3 on 2026-05-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0036_alter_historicaloficio_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioJudicial',
            fields=[
                ('oficio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oficios.oficio')),
            ],
            options={
                'verbose_name': 'Oficio Judicial',
                'verbose_name_plural': 'Oficios Judiciales',
                'ordering': ['-fecha_emision'],
            },
            bases=('oficios.oficio',),
        ),
        migrations.CreateModel(
            name='OficioMPA',
            fields=[
                ('oficio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oficios.oficio')),
            ],
            options={
                'verbose_name': 'Oficio MPA',
                'verbose_name_plural': 'Oficios MPA',
                'ordering': ['-fecha_emision'],
            },
            bases=('oficios.oficio',),
        ),
        migrations.AddField(
            model_name='historicaloficio',
            name='expediente',
            field=models.CharField(blank=True, help_text='Número de expediente relacionado al documento', max_length=50, null=True, verbose_name='Número de Expediente'),
        ),
        migrations.AddField(
            model_name='historicaloficio',
            name='tipo_documento',
            field=models.CharField(choices=[('oficio', 'Oficio'), ('judicial', 'Oficio Judicial'), ('mpa', 'Oficio MPA'), ('provincial', 'Oficio Provincial'), ('nota', 'Nota')], default='oficio', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='expediente',
            field=models.CharField(blank=True, help_text='Número de expediente relacionado al documento', max_length=50, null=True, verbose_name='Número de Expediente'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='tipo_documento',
            field=models.CharField(choices=[('oficio', 'Oficio'), ('judicial', 'Oficio Judicial'), ('mpa', 'Oficio MPA'), ('provincial', 'Oficio Provincial'), ('nota', 'Nota')], default='oficio', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
