# Generated by Django 5.2.3 on 2026-05-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0037_oficiojudicial_oficiompa_historicaloficio_expediente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('oficio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oficios.oficio')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha_emision'],
            },
            bases=('oficios.oficio',),
        ),
    ]
