# Generated by Django 5.2.3 on 2026-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0038_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloficio',
            name='tipo_documento',
            field=models.CharField(choices=[('oficio', 'Oficio'), ('judicial', 'Oficio Judicial'), ('mpa', 'Oficio MPA'), ('nacional', 'Oficio Nacional'), ('nota', 'Nota')], default='oficio', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='tipo_documento',
            field=models.CharField(choices=[('oficio', 'Oficio'), ('judicial', 'Oficio Judicial'), ('mpa', 'Oficio MPA'), ('nacional', 'Oficio Nacional'), ('nota', 'Nota')], default='oficio', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
