# Generated by Django 5.2.3 on 2026-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0039_alter_historicaloficio_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloficio',
            name='numero_interno',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador utilizado internamente para registrar el oficio.', max_length=50, verbose_name='Número interno'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='numero_interno',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador utilizado internamente para registrar el oficio.', max_length=50, verbose_name='Número interno'),
        ),
    ]
