# Generated by Django 5.2.3 on 2026-09-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0040_historicaloficio_numero_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloficio',
            name='revision_pendiente',
            field=models.BooleanField(default=False, editable=False, verbose_name='Corrección pendiente de respuesta'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='revision_pendiente',
            field=models.BooleanField(default=False, editable=False, verbose_name='Corrección pendiente de respuesta'),
        ),
        migrations.AlterField(
            model_name='historicaloficio',
            name='estado',
            field=models.CharField(choices=[('cargado', 'Cargado'), ('asignado', 'Asignado'), ('derivado', 'Derivado'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto'), ('en_revision', 'En revisión'), ('incompetencia', 'Incompetencia')], default='cargado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('cargado', 'Cargado'), ('asignado', 'Asignado'), ('derivado', 'Derivado'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto'), ('en_revision', 'En revisión'), ('incompetencia', 'Incompetencia')], max_length=20, null=True, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='movimientooficio',
            name='estado_nuevo',
            field=models.CharField(choices=[('cargado', 'Cargado'), ('asignado', 'Asignado'), ('derivado', 'Derivado'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto'), ('en_revision', 'En revisión'), ('incompetencia', 'Incompetencia')], max_length=20, verbose_name='Nuevo Estado'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='estado',
            field=models.CharField(choices=[('cargado', 'Cargado'), ('asignado', 'Asignado'), ('derivado', 'Derivado'), ('respondido', 'Respondido'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto'), ('en_revision', 'En revisión'), ('incompetencia', 'Incompetencia')], default='cargado', max_length=20, verbose_name='Estado'),
        ),
    ]
