# Generated by Django 5.2.3 on 2026-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0041_historicaloficio_revision_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloficio',
            name='grupo_creacion',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Grupo de creación múltiple'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='grupo_creacion',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Grupo de creación múltiple'),
        ),
        migrations.AddConstraint(
            model_name='oficio',
            constraint=models.UniqueConstraint(fields=('grupo_creacion', 'institucion'), name='oficio_grupo_institucion_unica'),
        ),
    ]
