# Generated by Django 5.2.3 on 2026-09-18 12:49

import django.core.validators
import oficios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0042_historicaloficio_grupo_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloficio',
            name='archivo_pdf',
            field=models.TextField(blank=True, help_text='Sube el archivo PDF, ZIP o RAR del oficio. Tamaño máximo: 10MB.', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar'], message='Solo se permiten archivos PDF, ZIP o RAR.')], verbose_name='Archivo adjunto del oficio'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Sube el archivo PDF, ZIP o RAR del oficio. Tamaño máximo: 10MB.', null=True, upload_to=oficios.models.oficio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar'], message='Solo se permiten archivos PDF, ZIP o RAR.')], verbose_name='Archivo adjunto del oficio'),
        ),
    ]
