# Generated by Django 5.2.7 on 2025-10-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id_ninos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nac', models.DateField()),
            ],
            options={
                'verbose_name': 'Niño',
                'verbose_name_plural': 'Niños',
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id_partes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('vinculo', models.CharField(help_text='Parentesco o relación con el niño', max_length=100)),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
            },
        ),
    ]
