# Generated by Django 5.2.7 on 2025-10-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='vinculo',
        ),
    ]
