# Generated by Django 5.2.7 on 2025-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_parte_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nino',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nino',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
