# Generated by Django 5.2.7 on 2025-10-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_nino_direccion_alter_nino_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nino',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad en años, si no se conoce la fecha de nacimiento', null=True),
        ),
    ]
