# Generated by Django 5.2.7 on 2025-10-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_nino_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
