# Generated by Django 5.2.3 on 2026-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_parte_telefono_alter_parte_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
