# Generated by Django 5.2.3 on 2026-06-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_historicalnino_historicalparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnino',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='nino',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
